name: run python script

on:
  workflow_dispatch:
    inputs:
  schedule:
    - cron: '*/3 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # 可以根据需要指定不同的Python版本
    - name: Run Python script
      run: python test/print.py  # 运行 Python 脚本